---
vxflexos_provisioner_namespace: 'vxflexos'
vxflexos_provisioner_username: 'admin'
vxflexos_provisioner_password: 'secret'
vxflexos_provisioner_systemname: 'system name'
vxflexos_provisioner_restgateway: 'https://192.168.1.1'
vxflexos_provisioner_storagepool: 'sp'
vxflexos_provisioner_mdmip: '192.168.1.1'
vxflexos_provisioner_volumenameprefix: 'k8s'
vxflexos_provisioner_controllercount: 1
vxflexos_provisioner_vxflexosbinpath: /bin/emc
vxflexos_provisioner_enablesnapshotcgdelete: "false"
vxflexos_provisioner_enablelistvolumesnapshot: "false"
vxflexos_provisioner_storageclass_name: vxflexos
vxflexos_provisioner_storageclass_isdefault: "true"
vxflexos_provisioner_storageclass_reclaimpolicy: Delete